services:
  - type: web
    name: task-manager-backend
    env: java
    buildCommand: cd backend/backend && mvn clean install
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        value: "postgresql://taskmanager_ck0x_user:87ByaS05xtt3vRBDwrVRE19xT5fwRCKe@dpg-ctu552i3esus7399d7bg-a.frankfurt-postgres.render.com/taskmanager_ck0x"
      - key: DATABASE_USERNAME
        value: "taskmanager_ck0x_user"
      - key: DATABASE_PASSWORD
        value: "87ByaS05xtt3vRBDwrVRE19xT5fwRCKe"
